backend:
  name: github
  repo: FeodalherreN/challepallecolle.space
  branch: main
  base_url: https://decap-cms-oauth.vercel.app
  auth_endpoint: /api/auth


media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "sale"
    label: "Sale"
    folder: "src/assets/collections"
    create: true
    extension: "md"
    format: "frontmatter"
    sortable_fields: ["order", "title"]
    fields:
      - { label: "Order", name: "order", widget: "number", default: 0, hint: "Lower numbers appear first" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "upcoming"
    label: "Upcoming"
    folder: "src/assets/upcoming"
    create: true
    extension: "md"
    format: "frontmatter"
    sortable_fields: ["order", "title"]
    fields:
      - { label: "Order", name: "order", widget: "number", default: 0, hint: "Lower numbers appear first" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }